import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input type="text" />
        <input type="password" />

        <p>
          <Link href="/">ログイン</Link>
        </p>
      </main>
    </div>
  )
}

export default Home

// export async function getServerSideProps() {
//   return {
//     props: {}, // ページコンポーネントにpropsとして渡されます。
//   }
// }
